version: '3.8'

services:
  ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_personal_assistant
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
