---
# Ansible Playbook — Provision and Configure AI Assistant Host

- name: Setup AI-Powered Personal Assistant
  hosts: localhost
  become: yes

  vars:
    python_version: "3.11"
    app_directory: "/opt/ai-assistant"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - python3-pip
          - docker.io
          - git
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'

    - name: Clone repository (if not already)
      git:
        repo: 'https://github.com/Trojan3877/AI-Powered-personal-Assistant.git'
        dest: "{{ app_directory }}"

    - name: Install Python requirements
      pip:
        requirements: "{{ app_directory }}/requirements.txt"
